### ISSUE TITLE
no matches found: configureRepositories.repositories[0].name=stable

### ISSUE THREAD

**Issue by harik8** [stefanprodan/gitops-helm-workshop#13]
I followed the given steps in https://helm.workshop.flagger.dev/prerequisites/#flux.
But it failed at helmv3 upgrade step. 

helmv3 upgrade -i helm-operator fluxcd/helm-operator --wait \\                                                                                             
--namespace fluxcd \\
--set git.ssh.secretName=flux-git-deploy \\
--set git.pollInterval=1m \\
--set chartsSyncInterval=1m \\
--set configureRepositories.enable=true \\
--set configureRepositories.repositories[0].name=stable \\
--set configureRepositories.repositories[0].url=https://kubernetes-charts.storage.googleapis.com \\
--set extraEnvs[0].name=HELM_VERSION \\
--set extraEnvs[0].value=v3 \\
--set image.repository=docker.io/fluxcd/helm-operator-prerelease \\
--set image.tag=helm-v3-71bc9d62
zsh: no matches found: configureRepositories.repositories[0].name=stable

**Comment by stefanprodan** [comment]
From what you've pasted above the `\` is missing from all lines, should be:

```
helmv3 upgrade -i helm-operator fluxcd/helm-operator --wait \
--namespace fluxcd \
--set git.ssh.secretName=flux-git-deploy \
--set git.pollInterval=1m \
--set chartsSyncInterval=1m \
--set configureRepositories.enable=true \
--set configureRepositories.repositories[0].name=stable \
--set configureRepositories.repositories[0].url=https://kubernetes-charts.storage.googleapis.com \
--set extraEnvs[0].name=HELM_VERSION \
--set extraEnvs[0].value=v3 \
--set image.repository=docker.io/fluxcd/helm-operator-prerelease \
--set image.tag=helm-v3-71bc9d62
```

**Comment by harik8** [comment]
Thank you! I missed adding an escape character "\\". I've updated the comment.

**Comment by stefanprodan** [comment]
I've tested this with bash not zsh. One way would be to provide a values.yaml file instead of in-line args to helm.

**Comment by harik8** [comment]
It's working on bash. I use bash instead of zsh. Thank you! :)

**Comment by imjuanleonard** [comment]
I wonder why zsh doesn't work, can we reopen this?

**Comment by fabianomartinsrj** [comment]
The problem is probably with the square brackets.
You should enclose each line with a single quote:

```
--set 'configureRepositories.repositories[0].name'=stable \
